### ISSUE TITLE
Typeerror when attempting to write header

### ISSUE THREAD

**Issue by kylerchin** [entrostat/terminal-csv-splitter#1]
```kyler@pop-os:~/sunrise/kenneth-data-gang/csvforexceleurope$ terminal-csv-splitter ./eCheckbook_Datalafy2020csvforexceleurope.csv --lines=1000000
Splitting ./eCheckbook_Datalafy2020csvforexceleurope.csv into files of 1000000 lines each, headers are enabled...
Split ./eCheckbook_Datalafy2020csvforexceleurope.csv into 8 files!
Adding the following headers to 8 files...

ID NUMBER;FISCAL YEAR;DEPARTMENT NAME;VENDOR NAME;TRANSACTION DATE;DOLLAR AMOUNT;AUTHORITY;BUSINESS TAX REGISTRATION CERTIFICATE;GOVERNMENT ACTIVITY;FUND GROUP NAME;FUND TYPE;FUND NAME;FUND;ACCOUNT NAME;ACCOUNT CODE;TRANSACTION ID;EXPENDITURE TYPE;SETTLEMENT/JUDGMENT;FISCAL MONTH NUMBER;FISCAL YEAR-MONTH;FISCAL YEAR-QUARTER;CALENDAR MONTH NUMBER;CALENDAR MONTH/YEAR;CALENDAR MONTH;DATA SOURCE;AUTHORITY NAME;AUTHORITY LINK;DEPARTMENT NUMBER;PROGRAM;VENDOR ID;ZIP;PAYMENT METHOD;PAYMENT STATUS;INV NUM;INVOICE DUE DATE;INVOICE DISCOUNT DUE DATE;INV DATE;INV LINE;INVOICE DISTRIBUTION LINE;PO NUM;DESCRIPTION;DETAILED ITEM DESCRIPTION;UNIT PRICE;UNIT OF MEASURE;QUANTITY;SALES TAX PERCENT;SALES TAX;DISCOUNT;RECEIVER ID;PO DATE;PO LINE NUMBER;PROCUREMENT ORGANIZATION;BUYER NAME;SUPPLIER CITY;SUPPLIER COUNTRY;BU NAME;SITE LOCATION;ITEM CODE;ITEM CODE NAME;CURRENCY;VALUE OF SPEND;VENDOR NUM

Completed 1/8 files
    TypeError: first argument must be a string or instance of Error
kyler@pop-os:~/sunrise/kenneth-data-gang/csvforexceleurope$ 

```

**Comment by kerren** [comment]
Hi @kylerchin thanks for sending this issue through, I'm sorry that I missed this :see_no_evil:

I'll try to get the error handling to show the error before the end of the week. I know it's way after you posted this but if you'd be willing to help me out, I'd really appreciate it if you could run it again (once I let you know the new version is up) and post the error message back here!

**Comment by kylerchin** [comment]
Hi Kerren! Thank you so much for getting back to me! Let me know when it's
up so I can run it again! :)

Looking forward to using this to split my csvs to import into Tableau!

**Comment by kylerchin** [comment]
Is this fixed yet?

**Comment by kerren** [comment]
Not just yet, I'm going to try to have the new release later today!

**Comment by kerren** [comment]
Hey @kylerchin can you please try the latest package when you have a chance?

`npm install -g terminal-csv-splitter@latest`

This should give you version 1.2.0 and we'll see how that goes!

**Comment by kerren** [comment]
Hey @kylerchin,

Let me know if you get a chance to test the changes here! I'll close off this bug at the end of the month :)
